/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class'],
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        background: '#222831',
        foreground: '#DFD0B8',
        card: '#393E46',
        'card-foreground': '#DFD0B8',
        popover: '#393E46',
        'popover-foreground': '#DFD0B8',
        primary: '#DFD0B8',
        'primary-foreground': '#222831',
        secondary: '#393E46',
        'secondary-foreground': '#DFD0B8',
        muted: '#2D343F',
        'muted-foreground': '#9CA3AF',
        accent: '#948979',
        'accent-foreground': '#222831',
        destructive: '#EF4444',
        'destructive-foreground': '#FFFFFF',
        border: '#4B5563',
        input: '#4B5563',
        ring: '#948979',
        safe: '#4ADE80',
        suspicious: '#FACC15',
        scam: '#EF4444',
        neutral: '#948979',
      },
      fontFamily: {
        heading: ['Outfit', 'sans-serif'],
        body: ['DM Sans', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      borderRadius: {
        lg: '0.5rem',
        md: 'calc(0.5rem - 2px)',
        sm: 'calc(0.5rem - 4px)',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};